name: My first github actions
on: [push]
jobs:
    print-hello-world:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Hello Wordl!!"
            - run: echo "Second Step"